services:
  registry:
    image: registry:2.8.2
    container_name: docker-registry
    restart: unless-stopped
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - registry_data:/var/lib/registry
      - ./auth:/auth:ro
      - ./config/registry.yml:/etc/docker/registry/config.yml:ro
    networks:
      - registry-network

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: unless-stopped
    environment:
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: "SB Registry"
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
      NGINX_PROXY_PASS_URL: "http://registry:5000"
      REGISTRY_URL: "${REGISTRY_URL}"
      SHOW_CATALOG_NB_TAGS: "true"
      CATALOG_MIN_BRANCHES: "1"
      CATALOG_MAX_BRANCHES: "1"
      TAGLIST_PAGE_SIZE: "100"
      REGISTRY_SECURED: "${REGISTRY_SECURED}"
      CATALOG_ELEMENTS_LIMIT: "1000"
      NGINX_PROXY_HEADER_X_FORWARDED_FOR: "$$proxy_add_x_forwarded_for"
      NGINX_PROXY_HEADER_X_REAL_IP: "$$remote_addr"
      NGINX_PROXY_HEADER_X_FORWARDED_PROTO: "$$scheme"
      NGINX_PROXY_HEADER_HOST: "$$http_host"
      NGINX_LISTEN_PORT: "80"
    depends_on:
      - registry
    networks:
      - registry-network


  nginx:
    image: nginx:alpine
    container_name: registry-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./auth:/etc/nginx/auth:ro
      - nginx-logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      - registry
      - registry-ui
    networks:
      - registry-network

volumes:
  registry_data:
    driver: local
  nginx-logs:
    driver: local

networks:
  registry-network:
    driver: bridge
