version: '3.8'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: unless-stopped
    ports:
      - "${REGISTRY_PORT:-5000}:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - registry_data:/var/lib/registry
      - ./auth:/auth:ro
      - ./certs:/certs:ro
      - ./config/registry.yml:/etc/docker/registry/config.yml:ro
    networks:
      - registry-network

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: unless-stopped
    ports:
      - "${REGISTRY_UI_PORT:-8080}:80"
    environment:
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: "Docker Registry"
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
      NGINX_PROXY_PASS_URL: "http://registry:5000"
      REGISTRY_URL: "http://localhost:5000"
      SHOW_CATALOG_NB_TAGS: "true"
      CATALOG_MIN_BRANCHES: "1"
      CATALOG_MAX_BRANCHES: "1"
      TAGLIST_PAGE_SIZE: "100"
      REGISTRY_SECURED: "false"
      CATALOG_ELEMENTS_LIMIT: "1000"
      NGINX_PROXY_HEADER_X_FORWARDED_FOR: "$$proxy_add_x_forwarded_for"
      NGINX_PROXY_HEADER_X_REAL_IP: "$$remote_addr"
      NGINX_PROXY_HEADER_X_FORWARDED_PROTO: "$$scheme"
      NGINX_PROXY_HEADER_HOST: "$$http_host"
      NGINX_LISTEN_PORT: "80"
    depends_on:
      - registry
    networks:
      - registry-network

  trivy:
    image: aquasec/trivy:latest
    container_name: trivy-scanner
    restart: unless-stopped
    ports:
      - "${TRIVY_PORT:-8081}:8080"
    command: server --listen 0.0.0.0:8080 --cache-dir /cache --debug
    volumes:
      - trivy_cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TRIVY_DEBUG: "true"
      TRIVY_CACHE_DIR: /cache
    networks:
      - registry-network

  nginx:
    image: nginx:alpine
    container_name: registry-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - registry
      - registry-ui
    networks:
      - registry-network
    profiles:
      - production

volumes:
  registry_data:
    driver: local
  trivy_cache:
    driver: local

networks:
  registry-network:
    driver: bridge
